version: "3"
tasks:
  gen:
    cmds:
      - go generate
  build:
    dir: cmd/web
    cmds:
      - GOARCH=wasm GOOS=js go build -o static/web/app.wasm
      - go build  -o static/app
      - cd static && ./app && rm ./app
  web:
    deps: [build]
    dir: cmd/web/static
    cmds:
      - go run ../tools/server
  clear:
    dir: cmd
    cmds:
      - rm -rf ndor/examples/*.html
      - rm -rf web/examples/*.png
      - rm -rf web/static/web
      - rm -f web/static/*.js
      - rm -f web/static/*.html
      - rm -f web/static/manifest*
      - rm -f web/static/app.css
  cli:
    cmds:
      - go run ./cmd/ndor {{.CLI_ARGS}}
