version: '3'
tasks:
  gen:
    cmds:
      - go generate
  build:
    dir: cmd/web
    cmds:
      - GOARCH=wasm GOOS=js go build -o static/web/app.wasm
      - go build -o static/app
      - cd static && ./app
      - rm static/app
  run:
    deps:
      - task: build
    dir: cmd/web
    cmds:
      - cd static && go run ../tools/server
  clear:
    dir: cmd/web/static
    cmds:
      - rm -rf web
      - rm -f *.js
      - rm -f *.html
      - rm -f manifest*
      - rm -f app.css
      - rm -rf .git
      - rm -f ../../../examples/*.png
  cli:
    cmds:
      - go run ./cmd/ndor {{.CLI_ARGS}}
