---
apiVersion: v1
kind: Service
metadata:
  name: ndor
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ndor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndor
  labels:
    app.kubernetes.io/name: ndor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ndor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ndor
    spec:
      containers:
        - name: ndor
          image: "ndor:0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits: 
              memory: "1Gi"
              cpu: "1"
            requests: 
              memory: "1Gi"
              cpu: "1"