// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AlertError(arg1:string):Promise<void>;

export function GenImage(arg1:string):Promise<{[key: string]: string}>;
